# Generated by Django 4.1.4 on 2022-12-23 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_device_games_alter_device_name_and_more'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='favourite_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.game'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='favourite_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.genre'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='main_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.device'),
        ),
    ]
