# Generated by Django 4.1.4 on 2022-12-21 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Game name')),
                ('image', models.URLField(verbose_name='Game image link')),
                ('developer', models.CharField(max_length=30, verbose_name='Developer name')),
                ('developer_site_link', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('synopsis', models.TextField(blank=True, max_length=150, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Genre name')),
                ('description', models.TextField(max_length=150)),
                ('games', models.ManyToManyField(to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Device name')),
                ('maker', models.CharField(max_length=30, verbose_name='Device maker')),
                ('image', models.URLField(verbose_name='Device image link')),
                ('release_date', models.DateField()),
                ('games', models.ManyToManyField(to='games.game')),
            ],
        ),
    ]
