# Generated by Django 4.1.4 on 2022-12-23 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='games',
            field=models.ManyToManyField(related_name='devices', to='games.game'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Device name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='games',
            field=models.ManyToManyField(related_name='genres', to='games.game'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=45, unique=True, verbose_name='Genre name'),
        ),
    ]
