# Generated by Django 4.1.4 on 2022-12-23 02:28

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_device_games_alter_device_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='games/', validators=[core.validators.validate_file_less_than_5mb], verbose_name='Game image'),
        ),
    ]
