# Generated by Django 4.1.4 on 2022-12-23 07:59

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(upload_to='consoles/', validators=[core.validators.validate_file_less_than_5mb]),
        ),
    ]
